# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - EShopWebApp1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build eShopOnWeb.sln --configuration Release
        
        # Tests
      - name: check pwd
        #run: ls -Rla
        run: pwd

        # Tests
      - name: check env
        run: echo ${{env.DOTNET_ROOT}}

      - name: dotnet publish web-app
        run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/webApp

      - name: dotnet publish web-api
        run: dotnet publish ./src/PublicApi/PublicApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/webAPI

      - name: Upload web-app artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .web-app
          path: ${{env.DOTNET_ROOT}}/webApp

      - name: Upload web-api artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .web-api
          path: ${{env.DOTNET_ROOT}}/webAPI

  deploy-web:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
        # Tests
      - name: get all dirs from current before downloading webapp
        run: ls -Rla

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .web-app
          
        # Tests
      - name: check url
        run: echo ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        
        # Tests
      - name: check pwd
        run: pwd
        
        # Tests
      - name: get all dirs from current after downloading webapp
        run: ls -Rla

      - name: Deploy to Azure Web App (first)
        id: deploy-to-webapp-1
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EShopWebApp1'
          slot-name: 'production'
          publish-profile: ${{ secrets.EShopWebApp1_Secret }}
          package: .

      - name: Deploy to Azure Web App (second)
        id: deploy-to-webapp-2
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EShopWebApp2'
          slot-name: 'production'
          publish-profile: ${{ secrets.EShopWebApp2_Secret }}
          package: .

  deploy-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
        # Tests
      - name: get all dirs from current before downloading webapp
        run: ls -Rla

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .web-api
          
        # Tests
      - name: check url
        run: echo ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        
        # Tests
      - name: check pwd
        run: pwd
        
        # Tests
      - name: get all dirs from current after downloading webapp
        run: ls -Rla

      - name: Deploy to Azure Web API project
        id: deploy-to-webapi
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'EShopWebAPI-Single'
          slot-name: 'production'
          publish-profile: ${{ secrets.EShopWebAPI_Secret }}
          package: .